@startuml
start

:Get URL from url-queue;
if (url is valid) then (yes)
if (url has changed) then (yes)
  :download url into HTML file;
  :compute hash of file;
  :add [url, hash(file)] to handled urls;
  :parse HTML file;
  repeat
    if (link is email) then (yes)
      :add link to email-queue;
    else (no)
      :add link to url-queue;
    endif
  repeat while (there are links in parsed file)
endif
else (no)
 :Raise exception;
endif
stop
@enduml
