@startuml

!includeurl https://raw.githubusercontent.com/ebbypeter/Archimate-PlantUML/master/Archimate.puml

'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

Grouping(swc, "Simple Web Crawler") {
Application_Process(crawler, "Crawler Control")
Application_Process(uh1, "URL Handler <I>1</I>")
Application_Process(uh2, "URL Handler <I>2</I>")
Application_Process(uhn, "URL Handler <I>n</I>")
Application_Process(emailHandler, "email Handler")

Technology_CommunicationNetwork(emailQueue, "email queue")
Technology_CommunicationNetwork(urlQueue, "URL queue")

Business_Object(listOfprocessedUrls, "Processed URLs")
Business_Object(listOfRejectedUrls, "Rejected URLs")
Business_Object(listOfknownEmails, "Known emails")

}

Technology_Artifact(urlfile, "URLs input file")
Technology_Artifact(emailfile, "email output file")

Rel_Serving(crawler, urlQueue, "Put")
Rel_Serving(crawler, urlfile, "Read")

Rel_Serving(uh1, urlQueue, "Put/Get")
Rel_Serving(uh2, urlQueue, "Put/Get")
Rel_Serving(uhn, urlQueue, "Put/Get")
'
Rel_Serving(uh1, emailQueue, "Put")
Rel_Serving(uh2, emailQueue, "Put")
Rel_Serving(uhn, emailQueue, "Put")

Rel_Serving_Up(uh1, listOfprocessedUrls, "Search/Append")
Rel_Serving_Up(uh2, listOfprocessedUrls, "Search/Append")
Rel_Serving_Up(uhn, listOfprocessedUrls, "Search/Append")

Rel_Serving_Up(uh1, listOfRejectedUrls, "Search/Append")
Rel_Serving_Up(uh2, listOfRejectedUrls, "Search/Append")
Rel_Serving_Up(uhn, listOfRejectedUrls, "Search/Append")

Rel_Serving_Up(emailHandler, emailQueue, "Get")
Rel_Serving(emailHandler,listOfknownEmails, "Search/Append")
Rel_Serving(emailHandler,emailfile, "Append")
'

@enduml
