@startuml
start

:Get URL from url-queue;
if (url is valid) then (yes)
if (url has changed) then (yes)
  :download url into HTML file;
  ':compute hash of file;
  :Add to <list> of processed URLs;
  :Parse HTML file;
  repeat
    :get href from file;
    if (href is email) then (yes)
      :add href to email-queue;
    else (no)
      :add href to url-queue;
    endif
  repeat while (while there are href in parsed file)
endif
else (no)
 :Add to <list> of rejected URLs;
endif
stop
@enduml
