@startuml

abstract class AbstractUrl {
  kvs
  is_uptodate()
  enqueue()
  save()
  {abstract} process()
}

class WebPageUrl {
 is_uptodate()
 save()
 process()
}

class EmailUrl {
 process()
}

class UnknownUrl {
 process()
}

AbstractUrl <|-- EmailUrl
AbstractUrl <|-- WebPageUrl
AbstractUrl <|-- UnknownUrl

@enduml