@startuml
start

repeat
: url-string == Get URL from url-queue;

':Increase depth;

:url-obj = Classify(url);

if (url-obj is new or changed) then (yes)
    :Process(url-obj);
endif

'repeat while (depth < maxdepth)
repeat while (forever)
@enduml
